language: perl
dist: bionic
addons:
  apt:
    packages:
      - liblocale-gettext-perl
      - libtext-wrapi18n-perl
      - libunicode-linebreak-perl
      - libtest-pod-perl
      - gettext
      - docbook-xml
      - docbook-xsl
      - docbook
      - xsltproc
      - texlive-binaries
      - texlive-latex-base
      - opensp
      - libsgmls-perl
      - docbook

before_install:
  - cpanm Locale::gettext
  - cpanm http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz
  - cpanm Text::WrapI18N
  - cpanm Unicode::GCString

install:
  - cpanm -v --installdeps --notest .  

script:
  - perl Build.PL
  - COLUMNS=120 ./Build verbose=1
  - ./Build test verbose=1

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.debian.org#po4a"
